// <auto-generated />
using System;
using GalacticApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GalacticApi.Data.Migrations
{
    [DbContext(typeof(GalacticApiContext))]
    partial class GalacticApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GalacticApi.Models.Asignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NombreAsignatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asignaturas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreAsignatura = "Lengua"
                        },
                        new
                        {
                            Id = 2,
                            NombreAsignatura = "Matematicas"
                        },
                        new
                        {
                            Id = 3,
                            NombreAsignatura = "Conocimiento del medio"
                        },
                        new
                        {
                            Id = 4,
                            NombreAsignatura = "Educación Artística"
                        },
                        new
                        {
                            Id = 5,
                            NombreAsignatura = "Ingles"
                        });
                });

            modelBuilder.Entity("GalacticApi.Models.AsignaturaJuego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("int");

                    b.Property<int>("IdAsignatura")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoJuego")
                        .HasColumnType("int");

                    b.Property<string>("JuegoAsignatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoJuegoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("TipoJuegoId");

                    b.ToTable("AsignaturaJuegos");
                });

            modelBuilder.Entity("GalacticApi.Models.Avatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CodigoJuego")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Premium")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RutaFoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Avatars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoJuego = "XXXXXX",
                            Premium = "N",
                            RutaFoto = ""
                        });
                });

            modelBuilder.Entity("GalacticApi.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"), 1L, 1);

                    b.Property<string>("NombreCurso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = 1,
                            NombreCurso = "1º Primaria"
                        },
                        new
                        {
                            CursoId = 2,
                            NombreCurso = "2º Primaria"
                        },
                        new
                        {
                            CursoId = 3,
                            NombreCurso = "3º Primaria"
                        },
                        new
                        {
                            CursoId = 4,
                            NombreCurso = "4º Primaria"
                        },
                        new
                        {
                            CursoId = 5,
                            NombreCurso = "5º Primaria"
                        },
                        new
                        {
                            CursoId = 6,
                            NombreCurso = "6º Primaria"
                        });
                });

            modelBuilder.Entity("GalacticApi.Models.Juego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AsignaturaJuegoId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAsignatura")
                        .HasColumnType("int");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoJuego")
                        .HasColumnType("int");

                    b.Property<string>("TemaJuego")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaJuegoId");

                    b.HasIndex("IdAsignatura");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdTipoJuego");

                    b.ToTable("Juegos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "XXXXXX",
                            IdAsignatura = 3,
                            IdCurso = 1,
                            IdTipoJuego = 1,
                            TemaJuego = "Geografía Basica"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "XXXXXX",
                            IdAsignatura = 3,
                            IdCurso = 1,
                            IdTipoJuego = 1,
                            TemaJuego = "Cultura General - 1"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "XXXXXX",
                            IdAsignatura = 3,
                            IdCurso = 1,
                            IdTipoJuego = 1,
                            TemaJuego = "Cultura General - 2"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "XXXXXX",
                            IdAsignatura = 5,
                            IdCurso = 1,
                            IdTipoJuego = 1,
                            TemaJuego = "Ingles Basic - 1"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "XXXXXX",
                            IdAsignatura = 5,
                            IdCurso = 1,
                            IdTipoJuego = 1,
                            TemaJuego = "Ingles Animals - 1"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "XXXXXX",
                            IdAsignatura = 2,
                            IdCurso = 1,
                            IdTipoJuego = 1,
                            TemaJuego = "Matematicas - General"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "XXXXXX",
                            IdAsignatura = 1,
                            IdCurso = 1,
                            IdTipoJuego = 1,
                            TemaJuego = "Lengua - 1"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "XXXXXX",
                            IdAsignatura = 1,
                            IdCurso = 1,
                            IdTipoJuego = 1,
                            TemaJuego = "Lengua - 1"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "XXXXXX",
                            IdAsignatura = 4,
                            IdCurso = 1,
                            IdTipoJuego = 1,
                            TemaJuego = "Plastica"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "XXXXXX",
                            IdAsignatura = 4,
                            IdCurso = 1,
                            IdTipoJuego = 1,
                            TemaJuego = "Musica"
                        });
                });

            modelBuilder.Entity("GalacticApi.Models.Pasapalabra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdJuego")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdJuego")
                        .IsUnique();

                    b.ToTable("Pasapalabras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdJuego = 1,
                            Name = "Geografía"
                        },
                        new
                        {
                            Id = 2,
                            IdJuego = 2,
                            Name = "Nombres de otras cosas pasapalabra"
                        },
                        new
                        {
                            Id = 3,
                            IdJuego = 3,
                            Name = "Nombres de otras cosas pasapalabra"
                        },
                        new
                        {
                            Id = 4,
                            IdJuego = 4,
                            Name = "Nombres de otras cosas pasapalabra"
                        },
                        new
                        {
                            Id = 5,
                            IdJuego = 5,
                            Name = "Nombres de otras cosas pasapalabra"
                        },
                        new
                        {
                            Id = 6,
                            IdJuego = 6,
                            Name = "Nombres de otras cosas pasapalabra"
                        },
                        new
                        {
                            Id = 7,
                            IdJuego = 7,
                            Name = "Nombres de otras cosas pasapalabra"
                        },
                        new
                        {
                            Id = 8,
                            IdJuego = 8,
                            Name = "Nombres de otras cosas pasapalabra"
                        },
                        new
                        {
                            Id = 9,
                            IdJuego = 9,
                            Name = "Nombres de otras cosas pasapalabra"
                        },
                        new
                        {
                            Id = 10,
                            IdJuego = 10,
                            Name = "Nombres de otras cosas pasapalabra"
                        });
                });

            modelBuilder.Entity("GalacticApi.Models.PreguntaPasapalabra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("PasapalabraId")
                        .HasColumnType("int");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PasapalabraId");

                    b.ToTable("PreguntaPasapalabras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Letra = "A",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por A: Continente al este de Europa ",
                            Respuesta = "Asia"
                        },
                        new
                        {
                            Id = 2,
                            Letra = "B",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por B: Capital de Alemania ",
                            Respuesta = "Berlín"
                        },
                        new
                        {
                            Id = 3,
                            Letra = "C",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por C: País de América del Sur ",
                            Respuesta = "Chile"
                        },
                        new
                        {
                            Id = 4,
                            Letra = "D",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por D: País de Europa ",
                            Respuesta = "Dinamarca"
                        },
                        new
                        {
                            Id = 5,
                            Letra = "E",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por E: País de África que es famoso por sus pirámides",
                            Respuesta = "Egipto"
                        },
                        new
                        {
                            Id = 6,
                            Letra = "F",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por F: País de Europa ",
                            Respuesta = "Francia"
                        },
                        new
                        {
                            Id = 7,
                            Letra = "G",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por G: País de América del Norte que",
                            Respuesta = "Guatemala"
                        },
                        new
                        {
                            Id = 8,
                            Letra = "H",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por H: País de América Central ",
                            Respuesta = "Honduras"
                        },
                        new
                        {
                            Id = 9,
                            Letra = "I",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por I: País de Europa ",
                            Respuesta = "Italia"
                        },
                        new
                        {
                            Id = 10,
                            Letra = "J",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por J:  País de Asia ",
                            Respuesta = "Japón"
                        },
                        new
                        {
                            Id = 11,
                            Letra = "K",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por K:  País de Asia ",
                            Respuesta = "Kazajistán"
                        },
                        new
                        {
                            Id = 12,
                            Letra = "L",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por L: País de Europa ",
                            Respuesta = "Lituania"
                        },
                        new
                        {
                            Id = 13,
                            Letra = "M",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por M:  País de África ",
                            Respuesta = "Marruecos"
                        },
                        new
                        {
                            Id = 14,
                            Letra = "N",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por N: País de Europa ",
                            Respuesta = "Noruega"
                        },
                        new
                        {
                            Id = 15,
                            Letra = "O",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por O:  País de Asia ",
                            Respuesta = "Omán"
                        },
                        new
                        {
                            Id = 16,
                            Letra = "P",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por P: País de Europa ",
                            Respuesta = "Portugal"
                        },
                        new
                        {
                            Id = 17,
                            Letra = "Q",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por Q: País de Asia ",
                            Respuesta = "Qatar"
                        },
                        new
                        {
                            Id = 18,
                            Letra = "R",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por R: País de Europa",
                            Respuesta = "Rusia"
                        },
                        new
                        {
                            Id = 19,
                            Letra = "S",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por S: País de Europa",
                            Respuesta = "Suecia"
                        },
                        new
                        {
                            Id = 20,
                            Letra = "T",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por T: País de Asia ",
                            Respuesta = "Tailandia"
                        },
                        new
                        {
                            Id = 21,
                            Letra = "U",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por U: País de Europa ",
                            Respuesta = "Ucrania"
                        },
                        new
                        {
                            Id = 22,
                            Letra = "V",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por V: País de Asia que",
                            Respuesta = "Vietnam"
                        },
                        new
                        {
                            Id = 23,
                            Letra = "W",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por W: País de Oceanía",
                            Respuesta = "Wallis y Futuna"
                        },
                        new
                        {
                            Id = 24,
                            Letra = "X",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por X: Ciudad de China",
                            Respuesta = "Xi'an"
                        },
                        new
                        {
                            Id = 25,
                            Letra = "Y",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por Y: País de Asia ",
                            Respuesta = "Yemen"
                        },
                        new
                        {
                            Id = 26,
                            Letra = "Z",
                            PasapalabraId = 1,
                            Pregunta = "Empieza por Z: País de África",
                            Respuesta = "Zambia"
                        },
                        new
                        {
                            Id = 27,
                            Letra = "A",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por A: Nombre de un animal volador conocido por su aguda visión",
                            Respuesta = "Águila"
                        },
                        new
                        {
                            Id = 28,
                            Letra = "B",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por B: Nombre de una fruta amarilla y curvada, popular en todo el mundo",
                            Respuesta = "Banana"
                        },
                        new
                        {
                            Id = 29,
                            Letra = "C",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por C: Nombre de un color primario, mezcla de azul y verde",
                            Respuesta = "Cian"
                        },
                        new
                        {
                            Id = 30,
                            Letra = "D",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por D: Nombre de un dinosaurio herbívoro con un cuello muy largo",
                            Respuesta = "Diplodocus"
                        },
                        new
                        {
                            Id = 31,
                            Letra = "E",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por E: Nombre del continente donde se encuentra España",
                            Respuesta = "Europa"
                        },
                        new
                        {
                            Id = 32,
                            Letra = "F",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por F: Nombre de un instrumento musical de viento muy utilizado en la música andina",
                            Respuesta = "Flauta"
                        },
                        new
                        {
                            Id = 33,
                            Letra = "G",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por G: Nombre de un deporte que se juega en un campo con 18 hoyos",
                            Respuesta = "Golf"
                        },
                        new
                        {
                            Id = 34,
                            Letra = "H",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por H: Nombre del tercer planeta del sistema solar en algunas lenguas",
                            Respuesta = "Helio"
                        },
                        new
                        {
                            Id = 35,
                            Letra = "I",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por I: Nombre de un país europeo famoso por su comida y su forma de bota",
                            Respuesta = "Italia"
                        },
                        new
                        {
                            Id = 36,
                            Letra = "J",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por J: Nombre del séptimo mes del año",
                            Respuesta = "Julio"
                        },
                        new
                        {
                            Id = 37,
                            Letra = "K",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por K: Nombre de un arte marcial japonés",
                            Respuesta = "Karate"
                        },
                        new
                        {
                            Id = 38,
                            Letra = "L",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por L: Nombre de un instrumento de cuerda similar a una guitarra pequeña",
                            Respuesta = "Laúd"
                        },
                        new
                        {
                            Id = 39,
                            Letra = "M",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por M: Nombre de un mar ubicado entre Europa, Asia y África",
                            Respuesta = "Mediterráneo"
                        },
                        new
                        {
                            Id = 40,
                            Letra = "N",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por N: Nombre de un fenómeno meteorológico blanco y frío que cae del cielo",
                            Respuesta = "Nieve"
                        },
                        new
                        {
                            Id = 41,
                            Letra = "O",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por O: Nombre de un mamífero marino grande y blanco y negro",
                            Respuesta = "Orca"
                        },
                        new
                        {
                            Id = 42,
                            Letra = "P",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por P: Nombre de un país europeo conocido por sus vinos y cuya capital es Lisboa",
                            Respuesta = "Portugal"
                        },
                        new
                        {
                            Id = 43,
                            Letra = "Q",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por Q: Nombre de un famoso caricaturista argentino creador de Mafalda",
                            Respuesta = "Quino"
                        },
                        new
                        {
                            Id = 44,
                            Letra = "R",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por R: Nombre de una figura geométrica de cuatro lados con ángulos rectos",
                            Respuesta = "Rectángulo"
                        },
                        new
                        {
                            Id = 45,
                            Letra = "S",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por S: Nombre de una ciudad española famosa por su catedral y su feria de abril",
                            Respuesta = "Sevilla"
                        },
                        new
                        {
                            Id = 46,
                            Letra = "T",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por T: Nombre de un país euroasiático que tiene a Estambul como una de sus ciudades",
                            Respuesta = "Turquía"
                        },
                        new
                        {
                            Id = 47,
                            Letra = "U",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por U: Nombre del séptimo planeta del sistema solar",
                            Respuesta = "Urano"
                        },
                        new
                        {
                            Id = 48,
                            Letra = "V",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por V: Nombre de un instrumento musical de cuerda, similar al violonchelo pero más pequeño",
                            Respuesta = "Violín"
                        },
                        new
                        {
                            Id = 49,
                            Letra = "W",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por W: Nombre de un famoso parque de atracciones en Florida",
                            Respuesta = "Walt Disney World"
                        },
                        new
                        {
                            Id = 50,
                            Letra = "X",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por X: Nombre de un instrumento de percusión con placas de madera",
                            Respuesta = "Xilófono"
                        },
                        new
                        {
                            Id = 51,
                            Letra = "Y",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por Y: Nombre de un río muy largo en China",
                            Respuesta = "Yangtsé"
                        },
                        new
                        {
                            Id = 52,
                            Letra = "Z",
                            PasapalabraId = 2,
                            Pregunta = "Empieza por Z: Nombre de un mamífero con rayas blancas y negras",
                            Respuesta = "Zebra"
                        },
                        new
                        {
                            Id = 53,
                            Letra = "A",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por A: Nombre de un famoso científico que desarrolló la teoría de la relatividad",
                            Respuesta = "Einstein"
                        },
                        new
                        {
                            Id = 54,
                            Letra = "B",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por B: Nombre de una danza tradicional argentina y uruguaya",
                            Respuesta = "Bailongo"
                        },
                        new
                        {
                            Id = 55,
                            Letra = "C",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por C: Nombre del inventor del teléfono",
                            Respuesta = "Bell"
                        },
                        new
                        {
                            Id = 56,
                            Letra = "D",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por D: Nombre del pintor surrealista español conocido por sus excéntricas obras",
                            Respuesta = "Dalí"
                        },
                        new
                        {
                            Id = 57,
                            Letra = "E",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por E: Nombre del mayor océano del mundo",
                            Respuesta = "Pacífico"
                        },
                        new
                        {
                            Id = 58,
                            Letra = "F",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por F: Nombre del autor del libro 'El principito'",
                            Respuesta = "Saint-Exupéry"
                        },
                        new
                        {
                            Id = 59,
                            Letra = "G",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por G: Nombre del metal más ligero",
                            Respuesta = "Litio"
                        },
                        new
                        {
                            Id = 60,
                            Letra = "H",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por H: Nombre de la isla donde se encuentra la estatua del Cristo Redentor",
                            Respuesta = "Corcovado"
                        },
                        new
                        {
                            Id = 61,
                            Letra = "I",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por I: Nombre de un famoso arquitecto español conocido por su obra 'La Sagrada Familia'",
                            Respuesta = "Gaudí"
                        },
                        new
                        {
                            Id = 62,
                            Letra = "J",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por J: Nombre de un famoso tenista suizo",
                            Respuesta = "Federer"
                        },
                        new
                        {
                            Id = 63,
                            Letra = "K",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por K: Nombre del presidente de Estados Unidos asesinado en 1963",
                            Respuesta = "Kennedy"
                        },
                        new
                        {
                            Id = 64,
                            Letra = "L",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por L: Nombre del mayor lago de agua dulce en África",
                            Respuesta = "Victoria"
                        },
                        new
                        {
                            Id = 65,
                            Letra = "M",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por M: Nombre de una famosa cadena de montañas en Sudamérica",
                            Respuesta = "Andes"
                        },
                        new
                        {
                            Id = 66,
                            Letra = "N",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por N: Nombre del autor de la novela 'Moby-Dick'",
                            Respuesta = "Melville"
                        },
                        new
                        {
                            Id = 67,
                            Letra = "O",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por O: Nombre del único mamífero que puede volar",
                            Respuesta = "Murciélago"
                        },
                        new
                        {
                            Id = 68,
                            Letra = "P",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por P: Nombre de la ciudad italiana famosa por su torre inclinada",
                            Respuesta = "Pisa"
                        },
                        new
                        {
                            Id = 69,
                            Letra = "Q",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por Q: Nombre del ave nacional de Guatemala",
                            Respuesta = "Quetzal"
                        },
                        new
                        {
                            Id = 70,
                            Letra = "R",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por R: Nombre del mayor desierto cálido del mundo",
                            Respuesta = "Sahara"
                        },
                        new
                        {
                            Id = 71,
                            Letra = "S",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por S: Nombre del satélite natural de la Tierra",
                            Respuesta = "Luna"
                        },
                        new
                        {
                            Id = 72,
                            Letra = "T",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por T: Nombre del lugar donde se realiza el festival de la flor de cerezos",
                            Respuesta = "Japón"
                        },
                        new
                        {
                            Id = 73,
                            Letra = "U",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por U: Nombre del país conocido por el Machu Picchu",
                            Respuesta = "Perú"
                        },
                        new
                        {
                            Id = 74,
                            Letra = "V",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por V: Nombre del pintor que cortó su propia oreja",
                            Respuesta = "Van Gogh"
                        },
                        new
                        {
                            Id = 75,
                            Letra = "W",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por W: Nombre del lugar donde se encuentra la Casa Blanca",
                            Respuesta = "Washington, D.C."
                        },
                        new
                        {
                            Id = 76,
                            Letra = "X",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por X: Nombre de la técnica de imagen médica que usa radiación",
                            Respuesta = "Rayos X"
                        },
                        new
                        {
                            Id = 77,
                            Letra = "Y",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por Y: Nombre de la flor nacional de Japón",
                            Respuesta = "Crisantemo"
                        },
                        new
                        {
                            Id = 78,
                            Letra = "Z",
                            PasapalabraId = 3,
                            Pregunta = "Empieza por Z: Nombre de un mineral precioso de color azul",
                            Respuesta = "Zafiro"
                        },
                        new
                        {
                            Id = 79,
                            Letra = "A",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por A: An animal that can fly and is known for its colorful feathers",
                            Respuesta = "Parrot"
                        },
                        new
                        {
                            Id = 80,
                            Letra = "B",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por B: A type of large animal that lives in rivers and lakes and can be very dangerous",
                            Respuesta = "Hippo"
                        },
                        new
                        {
                            Id = 81,
                            Letra = "C",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por C: A round, orange vegetable often used in soups and pies",
                            Respuesta = "Carrot"
                        },
                        new
                        {
                            Id = 82,
                            Letra = "D",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por D: The opposite of 'night'",
                            Respuesta = "Day"
                        },
                        new
                        {
                            Id = 83,
                            Letra = "E",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por E: The planet we live on",
                            Respuesta = "Earth"
                        },
                        new
                        {
                            Id = 84,
                            Letra = "F",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por F: What bird is known for its pink feathers and long legs?",
                            Respuesta = "Flamingo"
                        },
                        new
                        {
                            Id = 85,
                            Letra = "G",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por G: A color made by mixing blue and yellow",
                            Respuesta = "Green"
                        },
                        new
                        {
                            Id = 86,
                            Letra = "H",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por H: A common household pet that purrs",
                            Respuesta = "Cat"
                        },
                        new
                        {
                            Id = 87,
                            Letra = "I",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por I: Frozen water",
                            Respuesta = "Ice"
                        },
                        new
                        {
                            Id = 88,
                            Letra = "J",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por J: A sweet, red fruit often used to make jam",
                            Respuesta = "Strawberry"
                        },
                        new
                        {
                            Id = 89,
                            Letra = "K",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por K: A large bird that cannot fly and is native to Australia",
                            Respuesta = "Koala"
                        },
                        new
                        {
                            Id = 90,
                            Letra = "L",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por L: The opposite of 'dark'",
                            Respuesta = "Light"
                        },
                        new
                        {
                            Id = 91,
                            Letra = "M",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por M: A small, furry animal that lives in houses and likes cheese",
                            Respuesta = "Mouse"
                        },
                        new
                        {
                            Id = 92,
                            Letra = "N",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por N: The time of day when it is dark and people usually sleep",
                            Respuesta = "Night"
                        },
                        new
                        {
                            Id = 93,
                            Letra = "O",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por O: A fruit with a tough, spiky shell and sweet, yellow flesh",
                            Respuesta = "Pineapple"
                        },
                        new
                        {
                            Id = 94,
                            Letra = "P",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por P: A large mammal known for its trunk",
                            Respuesta = "Elephant"
                        },
                        new
                        {
                            Id = 95,
                            Letra = "Q",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por Q: A flying insect known for its painful sting",
                            Respuesta = "Wasp"
                        },
                        new
                        {
                            Id = 96,
                            Letra = "R",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por R: A large, round fruit that is often red or green and very juicy",
                            Respuesta = "Watermelon"
                        },
                        new
                        {
                            Id = 97,
                            Letra = "S",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por S: The opposite of 'slow'",
                            Respuesta = "Fast"
                        },
                        new
                        {
                            Id = 98,
                            Letra = "T",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por T: The opposite of 'short'",
                            Respuesta = "Tall"
                        },
                        new
                        {
                            Id = 99,
                            Letra = "U",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por U: The color of a clear sky",
                            Respuesta = "Blue"
                        },
                        new
                        {
                            Id = 100,
                            Letra = "V",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por V: A fruit that is often dried and used in cereals",
                            Respuesta = "Raisin"
                        },
                        new
                        {
                            Id = 101,
                            Letra = "W",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por W: The opposite of 'dry'",
                            Respuesta = "Wet"
                        },
                        new
                        {
                            Id = 102,
                            Letra = "X",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por X: A musical instrument that has wooden bars and is played with mallets",
                            Respuesta = "Xylophone"
                        },
                        new
                        {
                            Id = 103,
                            Letra = "Y",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por Y: A color that is the opposite of 'blue'",
                            Respuesta = "Yellow"
                        },
                        new
                        {
                            Id = 104,
                            Letra = "Z",
                            PasapalabraId = 4,
                            Pregunta = "Empieza por Z: A wild animal with black and white stripes",
                            Respuesta = "Zebra"
                        },
                        new
                        {
                            Id = 105,
                            Letra = "A",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por A: A type of large reptile that lives in water and on land",
                            Respuesta = "Alligator"
                        },
                        new
                        {
                            Id = 106,
                            Letra = "B",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por B: A flying insect that produces honey",
                            Respuesta = "Bee"
                        },
                        new
                        {
                            Id = 107,
                            Letra = "C",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por C: A round, orange vegetable often used in soups and pies",
                            Respuesta = "Carrot"
                        },
                        new
                        {
                            Id = 108,
                            Letra = "D",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por D: A small, round fruit that is often red or black",
                            Respuesta = "Date"
                        },
                        new
                        {
                            Id = 109,
                            Letra = "E",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por E: A flying insect known for its painful sting",
                            Respuesta = "Wasp"
                        },
                        new
                        {
                            Id = 110,
                            Letra = "F",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por F: An animal similar a cat",
                            Respuesta = "Fox"
                        },
                        new
                        {
                            Id = 111,
                            Letra = "G",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por G: A small, round fruit that is often red or black",
                            Respuesta = "Grape"
                        },
                        new
                        {
                            Id = 112,
                            Letra = "H",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por H: A tropical fruit with a hard shell and sweet, white flesh",
                            Respuesta = "Honeydew"
                        },
                        new
                        {
                            Id = 113,
                            Letra = "I",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por I: A large bird known for its long neck",
                            Respuesta = "Ibis"
                        },
                        new
                        {
                            Id = 114,
                            Letra = "J",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por J: A type of large bird that can't fly",
                            Respuesta = "Jabiru"
                        },
                        new
                        {
                            Id = 115,
                            Letra = "K",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por K: A marsupial native to Australia known for jumping",
                            Respuesta = "Kangaroo"
                        },
                        new
                        {
                            Id = 116,
                            Letra = "L",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por L: A South American mammal known for its wool",
                            Respuesta = "Llama"
                        },
                        new
                        {
                            Id = 117,
                            Letra = "M",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por M: A small carnivorous mammal known for its agility and speed",
                            Respuesta = "Mongoose"
                        },
                        new
                        {
                            Id = 118,
                            Letra = "N",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por N: A small marsupial native to Australia",
                            Respuesta = "Numbat"
                        },
                        new
                        {
                            Id = 119,
                            Letra = "O",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por O: A wild cat native to the Americas",
                            Respuesta = "Ocelot"
                        },
                        new
                        {
                            Id = 121,
                            Letra = "Q",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por Q: A small bird often hunted for sport",
                            Respuesta = "Quail"
                        },
                        new
                        {
                            Id = 123,
                            Letra = "S",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por S: A slow-moving mammal known for hanging from trees",
                            Respuesta = "Sloth"
                        },
                        new
                        {
                            Id = 124,
                            Letra = "T",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por T: A large bird often associated with Thanksgiving",
                            Respuesta = "Turkey"
                        },
                        new
                        {
                            Id = 125,
                            Letra = "U",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por U: A wild sheep native to the mountains of Asia",
                            Respuesta = "Urial"
                        },
                        new
                        {
                            Id = 126,
                            Letra = "V",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por V: A large bird known for scavenging carrion",
                            Respuesta = "Vulture"
                        },
                        new
                        {
                            Id = 127,
                            Letra = "W",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por W: A small marsupial native to Australia",
                            Respuesta = "Wallaby"
                        },
                        new
                        {
                            Id = 128,
                            Letra = "X",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por X: A small mammal native to Africa",
                            Respuesta = "Xerus"
                        },
                        new
                        {
                            Id = 129,
                            Letra = "Y",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por Y: A large mammal native to the Himalayas",
                            Respuesta = "Yak"
                        },
                        new
                        {
                            Id = 130,
                            Letra = "Z",
                            PasapalabraId = 5,
                            Pregunta = "Empieza por Z: A large striped mammal native to Africa",
                            Respuesta = "Zebra"
                        },
                        new
                        {
                            Id = 131,
                            Letra = "A",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por A: ¿Qué rama de las matemáticas se encarga del estudio de los números y las operaciones sobre ellos?",
                            Respuesta = "Aritmética"
                        },
                        new
                        {
                            Id = 132,
                            Letra = "B",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por B: ¿Cómo se llama la expresión algebraica que consta de dos términos?",
                            Respuesta = "Binomio"
                        },
                        new
                        {
                            Id = 133,
                            Letra = "C",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por C: ¿Cuál es la disciplina matemática que estudia el cambio y la acumulación mediante límites, derivadas e integrales?",
                            Respuesta = "Cálculo"
                        },
                        new
                        {
                            Id = 134,
                            Letra = "D",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por D: ¿Qué concepto matemático representa la tasa de cambio instantáneo de una función?",
                            Respuesta = "Derivada"
                        },
                        new
                        {
                            Id = 135,
                            Letra = "E",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por E: ¿Cómo se llama una igualdad matemática que contiene una o más incógnitas?",
                            Respuesta = "Ecuación"
                        },
                        new
                        {
                            Id = 136,
                            Letra = "F",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por F: ¿Qué tipo de relación matemática asigna a cada elemento de un conjunto exactamente un elemento de otro conjunto?",
                            Respuesta = "Función"
                        },
                        new
                        {
                            Id = 137,
                            Letra = "G",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por G: ¿Qué rama de las matemáticas se encarga del estudio de las formas, tamaños, y las propiedades del espacio?",
                            Respuesta = "Geometría"
                        },
                        new
                        {
                            Id = 138,
                            Letra = "H",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por H: ¿Cómo se llama el lado más largo de un triángulo rectángulo?",
                            Respuesta = "Hipotenusa"
                        },
                        new
                        {
                            Id = 139,
                            Letra = "I",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por I: ¿Qué concepto matemático representa el área bajo una curva o la acumulación de una cantidad?",
                            Respuesta = "Integral"
                        },
                        new
                        {
                            Id = 140,
                            Letra = "J",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por J: ¿Qué actividad matemática implica manipular números para llegar a un resultado específico?",
                            Respuesta = "Juego de números"
                        },
                        new
                        {
                            Id = 141,
                            Letra = "K",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por K: ¿Cómo se denomina la propiedad de un conjunto que indica su tamaño o cantidad de elementos?",
                            Respuesta = "Kardinalidad"
                        },
                        new
                        {
                            Id = 142,
                            Letra = "L",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por L: ¿Qué función matemática representa el exponente al que se debe elevar una base para obtener un número determinado?",
                            Respuesta = "Logaritmo"
                        },
                        new
                        {
                            Id = 143,
                            Letra = "M",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por M: ¿Cómo se llama una estructura matemática bidimensional que consta de filas y columnas de números?",
                            Respuesta = "Matriz"
                        },
                        new
                        {
                            Id = 144,
                            Letra = "N",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por N: ¿Qué término se utiliza para representar un concepto abstracto que denota cantidad o posición?",
                            Respuesta = "Número"
                        },
                        new
                        {
                            Id = 145,
                            Letra = "O",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por O: ¿Qué término se utiliza para referirse a una acción matemática como sumar, restar, multiplicar o dividir?",
                            Respuesta = "Operación"
                        },
                        new
                        {
                            Id = 146,
                            Letra = "P",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por P: ¿Cómo se llama una expresión algebraica que consta de términos sumados o restados que contienen variables elevadas a exponentes enteros?",
                            Respuesta = "Polinomio"
                        },
                        new
                        {
                            Id = 147,
                            Letra = "Q",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por Q: ¿Qué término se utiliza para el resultado de una división?",
                            Respuesta = "Quociente"
                        },
                        new
                        {
                            Id = 148,
                            Letra = "R",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por R: ¿Qué término se utiliza para indicar un valor que, cuando se eleva a un determinado exponente, produce un número determinado?",
                            Respuesta = "Raíz"
                        },
                        new
                        {
                            Id = 150,
                            Letra = "S",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por S: ¿Qué operación matemática se utiliza para combinar dos o más cantidades?",
                            Respuesta = "Suma"
                        },
                        new
                        {
                            Id = 151,
                            Letra = "T",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por T: ¿Qué función trigonométrica representa la razón entre el lado opuesto y el lado adyacente de un ángulo en un triángulo rectángulo?",
                            Respuesta = "Tangente"
                        },
                        new
                        {
                            Id = 152,
                            Letra = "U",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por U: ¿Qué término se utiliza para denotar una cantidad específica utilizada como estándar de medida?",
                            Respuesta = "Unidad"
                        },
                        new
                        {
                            Id = 153,
                            Letra = "V",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por V: ¿Cómo se llama una cantidad matemática que tiene magnitud y dirección?",
                            Respuesta = "Vector"
                        },
                        new
                        {
                            Id = 154,
                            Letra = "W",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por W: ¿Qué concepto matemático se utiliza en el álgebra lineal para determinar la independencia lineal de un conjunto de funciones?",
                            Respuesta = "Wronskiano"
                        },
                        new
                        {
                            Id = 155,
                            Letra = "X",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por X: ¿Qué término se utiliza para denotar el punto donde una gráfica intersecta el eje x?",
                            Respuesta = "X-intercepto"
                        },
                        new
                        {
                            Id = 156,
                            Letra = "Y",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por Y: ¿Qué término se utiliza para denotar el punto donde una gráfica intersecta el eje y?",
                            Respuesta = "Y-intercepto"
                        },
                        new
                        {
                            Id = 157,
                            Letra = "Z",
                            PasapalabraId = 6,
                            Pregunta = "Empieza por Z: En ingles, ¿Cómo se llama el número que representa la ausencia de cantidad o valor?",
                            Respuesta = "Zero (cero)"
                        });
                });

            modelBuilder.Entity("GalacticApi.Models.Resultados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdJuego")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<double>("Resultado")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdJuego");

                    b.HasIndex("IdUsuario");

                    b.ToTable("resultados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdJuego = 1,
                            IdUsuario = 1,
                            Resultado = 0.0
                        });
                });

            modelBuilder.Entity("GalacticApi.Models.TipoJuego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoJuegos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tipo = "Pasapalabra"
                        });
                });

            modelBuilder.Entity("GalacticApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AvatarId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 1,
                            Email = "aaron@svalero.com",
                            Name = "Aaron",
                            Password = "1234",
                            Rol = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 1,
                            Email = "antonio@svalero.com",
                            Name = "Antonio",
                            Password = "1234",
                            Rol = "Profesor"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 1,
                            Email = "alex@svalero.com",
                            Name = "Alex",
                            Password = "1234",
                            Rol = "Alumno"
                        });
                });

            modelBuilder.Entity("GalacticApi.Models.AsignaturaJuego", b =>
                {
                    b.HasOne("GalacticApi.Models.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticApi.Models.TipoJuego", "TipoJuego")
                        .WithMany()
                        .HasForeignKey("TipoJuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("TipoJuego");
                });

            modelBuilder.Entity("GalacticApi.Models.Juego", b =>
                {
                    b.HasOne("GalacticApi.Models.AsignaturaJuego", null)
                        .WithMany("Juegos")
                        .HasForeignKey("AsignaturaJuegoId");

                    b.HasOne("GalacticApi.Models.Asignatura", "Asignatura")
                        .WithMany("Juegos")
                        .HasForeignKey("IdAsignatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticApi.Models.Curso", "Curso")
                        .WithMany("Juegos")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticApi.Models.TipoJuego", "TipoJuego")
                        .WithMany("Juegos")
                        .HasForeignKey("IdTipoJuego")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Curso");

                    b.Navigation("TipoJuego");
                });

            modelBuilder.Entity("GalacticApi.Models.Pasapalabra", b =>
                {
                    b.HasOne("GalacticApi.Models.Juego", "Juego")
                        .WithOne("Pasapalabra")
                        .HasForeignKey("GalacticApi.Models.Pasapalabra", "IdJuego")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Juego");
                });

            modelBuilder.Entity("GalacticApi.Models.PreguntaPasapalabra", b =>
                {
                    b.HasOne("GalacticApi.Models.Pasapalabra", "Pasapalabra")
                        .WithMany("PreguntaPasapalabras")
                        .HasForeignKey("PasapalabraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pasapalabra");
                });

            modelBuilder.Entity("GalacticApi.Models.Resultados", b =>
                {
                    b.HasOne("GalacticApi.Models.Juego", "Juego")
                        .WithMany("Resultados")
                        .HasForeignKey("IdJuego")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalacticApi.Models.Usuario", "Usuario")
                        .WithMany("Resultados")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Juego");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GalacticApi.Models.Usuario", b =>
                {
                    b.HasOne("GalacticApi.Models.Avatar", "Avatar")
                        .WithMany("Usuarios")
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("GalacticApi.Models.Asignatura", b =>
                {
                    b.Navigation("Juegos");
                });

            modelBuilder.Entity("GalacticApi.Models.AsignaturaJuego", b =>
                {
                    b.Navigation("Juegos");
                });

            modelBuilder.Entity("GalacticApi.Models.Avatar", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GalacticApi.Models.Curso", b =>
                {
                    b.Navigation("Juegos");
                });

            modelBuilder.Entity("GalacticApi.Models.Juego", b =>
                {
                    b.Navigation("Pasapalabra")
                        .IsRequired();

                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("GalacticApi.Models.Pasapalabra", b =>
                {
                    b.Navigation("PreguntaPasapalabras");
                });

            modelBuilder.Entity("GalacticApi.Models.TipoJuego", b =>
                {
                    b.Navigation("Juegos");
                });

            modelBuilder.Entity("GalacticApi.Models.Usuario", b =>
                {
                    b.Navigation("Resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
